### ISSUE TITLE
Upgrade: Add maintenance DAGs

### ISSUE THREAD

**Issue by hancush** [Metro-Records/la-metro-dashboard#109]
Add maintenance DAGs to run `airflow clean` and [clean up log files](https://github.com/teamclairvoyant/airflow-maintenance-dags/blob/master/log-cleanup/airflow-log-cleanup.py).

**Comment by antidipyramid** [comment]
@hancush Is it reasonable to delete metadata and log files older than 30 days?

**Comment by hancush** [comment]
@antidipyramid Very!

**Comment by antidipyramid** [comment]
@hancush Also, should we be doing some sort of backup before running the `airflow db clean` command?

**Comment by hancush** [comment]
@antidipyramid The logs are pushed to S3.
