### ISSUE TITLE
Increase production dashboard server disk space

### ISSUE THREAD

**Issue by hancush** [Metro-Records/la-metro-dashboard#111]
Relevant docs: 

- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/step3-increase-size-of-data-volume.html
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/step4-extend-file-system.html

This walk through is also good: https://linuxhint.com/increase-disk-space-ec2/

**Comment by antidipyramid** [comment]
The production dashboard now has 50GB of disk space.

<img width="1124" alt="Screen Shot 2023-06-21 at 3 32 02 PM" src="https://github.com/Metro-Records/la-metro-dashboard/assets/36973363/1daf0c15-1098-4b1e-ba06-3156eb60947c">

**Comment by hancush** [comment]
Thanks, @antidipyramid!
